import "./globals.css";

export const metadata = {
  title: "Damru 2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`antialiased overflow-hidden`}>
        {children}
      </body>
    </html>
  );
}
